apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: null
    labels:
      kubernetes.io/metadata.name: spodlivoi
    name: spodlivoi
  spec: {}
  status:
    phase: Active
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: spodlivoidb
    namespace: spodlivoi
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: spodlivoibot
    namespace: spodlivoi
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: spodlivoibot
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: spodlivoibot
      spec:
        containers:
        - env:
          - name: TELEGRAM_BOT_TOKEN
            value: ${TELEGRAM_BOT_TOKEN}
          - name: TELEGRAM_BOT_USERNAME
            value: ${TELEGRAM_BOT_USERNAME}
          - name: TELEGRAM_BOT_ADMIN-CHAT-ID
            value: ${TELEGRAM_BOT_ADMIN_CHAT_ID}
          - name: SPRING_DATASOURCE_USERNAME
            value: spodlivoi
          - name: SPRING_DATASOURCE_PASSWORD
            value: spodlivoi
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://db:5432/spodlivoi
          - name: LOGGING_FILE_NAME
            value: /dev/null
          image: ghcr.io/tsunamaru/spodlivoibot/ci-build:latest
          imagePullPolicy: Always
          name: bot
          resources:
            limits:
              memory: 7Gi
            requests:
              cpu: 500m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - env:
          - name: POSTGRES_USER
            value: spodlivoi
          - name: POSTGRES_PASSWORD
            value: spodlivoi
          - name: POSTGRES_DB
            value: spodlivoi
          image: postgres:14-alpine
          imagePullPolicy: Always
          name: db
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: spodlivoidb
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: spodlivoidb
          persistentVolumeClaim:
            claimName: spodlivoidb
  status: {}
kind: List
metadata: {}