apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: ns-admin
    namespace: spodlivoi
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - secrets
    verbs:
    - create
    - get
    - update
    - list
    - watch
    - patch
  - apiGroups:
    - apps
    resources:
    - deployment
    verbs:
    - create
    - get
    - update
    - list
    - delete
    - watch
    - patch
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterroles
    - clusterrolebindings
    verbs:
    - create
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: ns-admin
    namespace: spodlivoi
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: ns-admin
  subjects:
  - kind: ServiceAccount
    name: ns-admin-sa
    namespace: spodlivoi
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ns-admin-sa
    namespace: spodlivoi
  secrets:
  - name: ns-admin-secret
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      kubernetes.io/service-account.name: ns-admin-sa
    creationTimestamp: null
    name: ns-admin-secret
    namespace: spodlivoi
  type: kubernetes.io/service-account-token
kind: List
metadata: {}