apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: spodlivoi
    name: spodlivoi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: spodlivoidb
    namespace: spodlivoi
    annotations:
      volume.beta.kubernetes.io/storage-class: "efs-sc"
  spec:
    storageClassName: efs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: spodlivoibot
    namespace: spodlivoi
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: spodlivoibot
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: spodlivoibot
      spec:
        containers:
        - env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: bot-secrets
          - name: TELEGRAM_BOT_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: bot-secrets
          - name: TELEGRAM_BOT_ADMIN-CHAT-ID
            valueFrom:
              secretKeyRef:
                key: adm_chat_id
                name: bot-secrets
                optional: true
          - name: SPRING_DATASOURCE_USERNAME
            value: spodlivoi
          - name: SPRING_DATASOURCE_PASSWORD
            value: spodlivoi
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://db-svc:5432/spodlivoi
          - name: LOGGING_FILE_NAME
            value: /dev/null
          image: ghcr.io/tsunamaru/spodlivoibot/ci-build:latest
          imagePullPolicy: Always
          name: bot
          resources:
            limits:
              memory: 7Gi
            requests:
              cpu: 500m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - env:
          - name: POSTGRES_USER
            value: spodlivoi
          - name: POSTGRES_PASSWORD
            value: spodlivoi
          - name: POSTGRES_DB
            value: spodlivoi
          image: postgres:14-alpine
          imagePullPolicy: Always
          name: db
          ports:
          - containerPort: 5432
            protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/postgresql
            name: spodlivoidb
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
        - name: spodlivoidb
          persistentVolumeClaim:
            claimName: spodlivoidb
- apiVersion: v1
  kind: Service
  metadata:
    name: db-svc
    namespace: spodlivoi
  spec:
    ports:
    - name: db
      port: 5432
    selector:
      app: spodlivoibot
    type: ClusterIP
kind: List
metadata: {}